### PR TITLE
Implement division feature

### PR DESCRIPTION
**Pull request by asifmahmud35**

### CODE REVIEW

**Review by Noman-1533 — CHANGES_REQUESTED** [review]
why two function of same name?

**Review by arafath-BS — CHANGES_REQUESTED** [review]
why you used two functions here

**Review by asifmahmud35 — COMMENTED** [review]
Changes are completed

**Review by Noman-1533 — APPROVED** [review]
Ok. Now it's looks good

**Review by arafath-BS — APPROVED** [review]
ok now

**Pull request merged**
